from __future__ import annotations
from backend.integrations.commerce.models import CommerceProductItem, ProductVariant

def _v(spin_id: str, name: str, pack_size: str, price: float, mrp: float, in_stock: bool = True) -> ProductVariant:
    return ProductVariant(spin_id=spin_id, name=name, pack_size=pack_size, price=price, mrp=mrp, in_stock=in_stock)

def _p(pid: str, name: str, cat: str, *variants: ProductVariant) -> CommerceProductItem:
    return CommerceProductItem(product_id=pid, name=name, category=cat, variants=list(variants))

MOCK_PRODUCTS: list[CommerceProductItem] = [
    _p('prod-milk', 'Amul Taaza Fresh Toned Milk', 'dairy', _v('SPIN-MILK-1L', 'Amul Taaza Milk 1L Pouch', '1 L', 66.0, 68.0, True), _v('SPIN-MILK-500ML', 'Amul Taaza Milk 500ml Pouch', '500 ml', 34.0, 35.0, True)),
    _p('prod-bread', 'Whole Wheat Brown Bread', 'bakery', _v('SPIN-BREAD-400G', 'Whole Wheat Bread 400g', '400 g', 50.0, 55.0, True)),
    _p('prod-eggs', 'Farm Fresh White Eggs', 'poultry', _v('SPIN-EGGS-12', 'Farm Fresh Eggs (12 pcs)', '12 pcs', 90.0, 95.0, True), _v('SPIN-EGGS-6', 'Farm Fresh Eggs (6 pcs)', '6 pcs', 48.0, 52.0, True)),
    _p('prod-tomato', 'Fresh Farm Hybrid Tomatoes', 'produce', _v('SPIN-TOMATO-500G', 'Hybrid Tomatoes 500g', '500 g', 32.0, 36.0, True), _v('SPIN-TOMATO-1KG', 'Hybrid Tomatoes 1kg', '1 kg', 60.0, 70.0, True)),
    _p('prod-coke', 'Coca-Cola (Coke) Original Taste', 'beverages', _v('SPIN-COKE-CAN', 'Coca-Cola (Coke) Can (300 ml)', '300 ml', 40.0, 40.0, True), _v('SPIN-COKE-750ML', 'Coca-Cola (Coke) Bottle (750 ml)', '750 ml', 45.0, 45.0, True)),
    _p('prod-maggi', 'Nestle Maggi 2-Minute Masala Instant Noodles', 'instant_food', _v('SPIN-MAGGI-4PACK', 'Maggi 2-Minute Masala Noodles (4-Pack)', '280 g', 56.0, 60.0, True)),
    _p('prod-atta', 'Aashirvaad Superior MP Whole Wheat Atta', 'flours', _v('SPIN-ATTA-1KG', 'Aashirvaad Whole Wheat Atta 1kg', '1 kg', 55.0, 60.0, True), _v('SPIN-ATTA-5KG', 'Aashirvaad Whole Wheat Atta 5kg', '5 kg', 245.0, 270.0, True)),
    _p('prod-rice', 'Daawat Rozana Super Basmati Rice', 'rice', _v('SPIN-RICE-1KG', 'Daawat Rozana Basmati Rice 1kg', '1 kg', 95.0, 110.0, True)),
    _p('prod-dal', 'Tata Sampann Unpolished Toor Dal', 'pulses', _v('SPIN-DAL-1KG', 'Tata Sampann Toor Dal 1kg', '1 kg', 165.0, 185.0, True)),
    _p('prod-sugar', 'Madhur Pure & Hygienic Sugar', 'staples', _v('SPIN-SUGAR-1KG', 'Madhur Pure Sugar (Cheeni) 1kg', '1 kg', 52.0, 56.0, True)),
    _p('prod-oil', 'Fortune Sunlite Refined Sunflower Oil', 'edible_oils', _v('SPIN-OIL-1L', 'Fortune Sunflower Oil 1L Pouch', '1 L', 140.0, 160.0, True)),
    _p('prod-butter', 'Amul Pasteurised Salted Butter', 'dairy', _v('SPIN-BUTTER-100G', 'Amul Salted Butter 100g', '100 g', 58.0, 60.0, True), _v('SPIN-BUTTER-500G', 'Amul Salted Butter 500g', '500 g', 275.0, 285.0, True)),
    _p('prod-paneer', 'Amul Fresh Malai Paneer', 'dairy', _v('SPIN-PANEER-200G', 'Amul Malai Paneer 200g', '200 g', 90.0, 95.0, True)),
    _p('prod-dahi', 'Amul Masti Dahi Curd', 'dairy', _v('SPIN-DAHI-400G', 'Amul Masti Dahi Curd 400g Pouch', '400 g', 35.0, 35.0, True)),
    _p('prod-yogurt', 'Epigamia Greek Yogurt Natural', 'dairy', _v('SPIN-GREEK-YOGURT-100G', 'Epigamia Greek Yogurt 100g', '100 g', 50.0, 50.0, True)),
    _p('prod-cheese', 'Amul Diced Mozzarella Blend Cheese', 'dairy', _v('SPIN-CHEESE-200G', 'Amul Mozzarella Diced Cheese 200g', '200 g', 110.0, 120.0, True)),
    _p('prod-pasta', 'Yu Zero Maida Penne Pasta', 'pasta', _v('SPIN-PASTA-PENNE-500G', 'Yu Zero Maida Penne Pasta 500g', '500 g', 49.0, 60.0, True)),
    _p('prod-sauce', 'Veeba Pasta & Pizza Sauce', 'sauces', _v('SPIN-VEEBA-SAUCE-280G', 'Veeba Pasta & Pizza Sauce 280g', '280 g', 79.0, 89.0, True)),
    _p('prod-garlic', 'Fresh Farm Garlic', 'produce', _v('SPIN-GARLIC-100G', 'Fresh Peeled Garlic 100g', '100 g', 25.0, 30.0, True)),
    _p('prod-ginger', 'Fresh Ginger (Adrak)', 'produce', _v('SPIN-GINGER-100G', 'Fresh Ginger Adrak 100g', '100 g', 20.0, 25.0, True)),
    _p('prod-onion', 'Fresh Farm Onions (Pyaz)', 'produce', _v('SPIN-ONION-1KG', 'Fresh Red Onions 1kg', '1 kg', 38.0, 45.0, True)),
    _p('prod-potato', 'Fresh Farm Potatoes (Aloo)', 'produce', _v('SPIN-POTATO-1KG', 'Fresh Baby Potatoes 1kg', '1 kg', 32.0, 40.0, True)),
    _p('prod-banana', 'Fresh Robusta Bananas', 'fruits', _v('SPIN-BANANA-6PCS', 'Fresh Robusta Bananas (6 pcs)', '6 pcs', 42.0, 50.0, True)),
    _p('prod-chocolate-dairymilk', 'Cadbury Dairy Milk Silk Chocolate', 'chocolates', _v('SPIN-DAIRYMILK-60G', 'Cadbury Dairy Milk Silk 60g', '60 g', 90.0, 90.0, True), _v('SPIN-DAIRYMILK-36G', 'Cadbury Dairy Milk Crackle 36g', '36 g', 50.0, 50.0, True)),
    _p('prod-chocolate-kitkat', 'Nestle KitKat Crisp Wafer Chocolate', 'chocolates', _v('SPIN-KITKAT-38G', 'Nestle KitKat 4 Finger 38g', '38 g', 30.0, 30.0, True)),
    _p('prod-chips-lays', "Lay's India's Magic Masala Potato Chips", 'snacks', _v('SPIN-LAYS-50G', "Lay's Magic Masala 50g", '50 g', 20.0, 20.0, True)),
    _p('prod-chips-kurkure', 'Kurkure Masala Munch Crisps', 'snacks', _v('SPIN-KURKURE-85G', 'Kurkure Masala Munch 85g', '85 g', 20.0, 20.0, True)),
    _p('prod-drink-thumsup', 'Thums Up Soft Drink', 'beverages', _v('SPIN-THUMSUP-750ML', 'Thums Up Bottle 750ml', '750 ml', 40.0, 40.0, True)),
    _p('prod-tea', 'Brooke Bond Red Label Strong Tea (Chai Patti)', 'tea', _v('SPIN-TEA-250G', 'Red Label Tea 250g', '250 g', 135.0, 150.0, True)),
    _p('prod-coffee', 'Nescafe Classic Instant Coffee', 'coffee', _v('SPIN-COFFEE-50G', 'Nescafe Classic Coffee Jar 50g', '50 g', 185.0, 200.0, True)),
    _p('prod-greentea', 'Tetley Green Tea Lemon & Honey', 'tea', _v('SPIN-GREENTEA-25BAGS', 'Tetley Lemon Honey Green Tea 25 Tea Bags', '25 bags', 160.0, 180.0, True)),
    _p('prod-crocin', 'Crocin Advance Paracetamol Pain & Fever Tablet', 'pharmacy', _v('SPIN-CROCIN-15TAB', 'Crocin Advance Paracetamol (15 Tablets)', '15 tabs', 32.0, 35.0, True)),
    _p('prod-strepsils', 'Strepsils Sore Throat Lozenges Orange', 'pharmacy', _v('SPIN-STREPSILS-8TAB', 'Strepsils Orange Lozenges (8 Tablets)', '8 tabs', 36.0, 40.0, True)),
    _p('prod-vicks', 'Vicks VapoRub Cold Relief Balm', 'pharmacy', _v('SPIN-VICKS-25ML', 'Vicks VapoRub Relief Balm 25ml', '25 ml', 65.0, 70.0, True)),
    _p('prod-bandaid', 'Hansaplast Medicated Band-Aids', 'pharmacy', _v('SPIN-BANDAID-10STRIPS', 'Hansaplast Band-Aid Strips (10 Strips)', '10 strips', 30.0, 35.0, True)),
    _p('prod-colgate', 'Colgate MaxFresh Spicy Fresh Red Gel Toothpaste', 'oral_care', _v('SPIN-COLGATE-150G', 'Colgate MaxFresh Red Gel 150g', '150 g', 110.0, 125.0, True)),
    _p('prod-dettol-handwash', 'Dettol Original Germ Protection Handwash Refill', 'hygiene', _v('SPIN-DETTOL-HW-175ML', 'Dettol Handwash Refill Pouch 175ml', '175 ml', 45.0, 50.0, True)),
    _p('prod-shampoo', 'Dove Daily Shine Gentle Care Shampoo', 'hair_care', _v('SPIN-DOVE-SHAMPOO-180ML', 'Dove Daily Shine Shampoo 180ml', '180 ml', 145.0, 170.0, True)),
    _p('prod-vim', 'Vim Lemon Dishwash Gel Liquid', 'cleaning', _v('SPIN-VIM-GEL-500ML', 'Vim Lemon Dishwash Liquid Gel 500ml', '500 ml', 105.0, 120.0, True)),
    _p('prod-harpic', 'Harpic Power Plus Disinfectant Toilet Cleaner', 'cleaning', _v('SPIN-HARPIC-500ML', 'Harpic Toilet Cleaner Original 500ml', '500 ml', 98.0, 105.0, True)),
    _p('prod-surfexcel', 'Surf Excel Easy Wash Detergent Powder', 'cleaning', _v('SPIN-SURFEXCEL-1KG', 'Surf Excel Detergent Powder 1kg', '1 kg', 140.0, 155.0, True)),
    _p('prod-garbage-bags', 'Shalimar Medium Disposable Garbage Bags', 'household', _v('SPIN-GARBAGE-BAGS-30PCS', 'Shalimar Black Garbage Bags (30 pcs)', '30 pcs', 75.0, 90.0, True)),
    _p('prod-batteries-aa', 'Duracell Ultra AA Alkaline Batteries', 'electronics', _v('SPIN-DURACELL-AA-4PCS', 'Duracell Ultra AA Batteries (4 pcs)', '4 pcs', 160.0, 180.0, True)),
    _p('prod-cable-typec', 'Portronics Fast Charging USB Type-C Cable', 'electronics', _v('SPIN-TYPEC-CABLE-1M', 'Portronics USB Type-C Cable 1m', '1 m', 149.0, 299.0, True)),
    _p('prod-allout', 'All Out Ultra Mosquito Repellent Machine + Refill', 'household', _v('SPIN-ALLOUT-COMBO', 'All Out Mosquito Repellent Machine with Liquid Refill', '1 pack', 110.0, 125.0, True)),
    _p('prod-agarbatti', 'Mangaldeep Sandalwood Agarbatti Incense Sticks', 'pooja', _v('SPIN-AGARBATTI-1PACK', 'Mangaldeep Sandal Agarbatti (Pack of 80)', '80 sticks', 50.0, 60.0, True)),
    _p('prod-camphor', 'Cycle Pure Pure Camphor / Kapoor Tablets', 'pooja', _v('SPIN-CAMPHOR-50G', 'Cycle Pure Camphor Kapoor 50g', '50 g', 65.0, 75.0, True)),
    _p('prod-almonds', 'Rostaa Roasted & Salted California Almonds', 'dry_fruits', _v('SPIN-ALMONDS-100G', 'Rostaa Roasted Salted Almonds 100g', '100 g', 115.0, 130.0, True)),
    _p('prod-garlic', 'Fresh Garlic (Lahsun)', 'produce', _v('SPIN-GARLIC-100G', 'Fresh Garlic 100g', '100 g', 38.0, 45.0, True)),
    _p('prod-ginger', 'Fresh Ginger (Adrak)', 'produce', _v('SPIN-GINGER-100G', 'Fresh Ginger 100g', '100 g', 35.0, 40.0, True)),
    _p('prod-mushroom', 'Fresh Button Mushrooms', 'produce', _v('SPIN-MUSHROOM-1PACK', 'Fresh Button Mushrooms 1 Pack', '200 g', 65.0, 75.0, True)),
    _p('prod-olive-oil', 'Figaro Extra Virgin Olive Oil', 'edible_oils', _v('SPIN-OLIVEOIL-250ML', 'Figaro Extra Virgin Olive Oil 250ml', '250 ml', 345.0, 375.0, True)),
    _p('prod-chips', "Lay's India's Magic Masala Potato Chips", 'snacks', _v('SPIN-LAYS-CHIPS-50G', "Lay's Magic Masala Potato Chips 50g", '50 g', 20.0, 20.0, True)),
    _p('prod-pepsi', 'Pepsi Original Taste Cold Drink', 'beverages', _v('SPIN-PEPSI-CAN-330ML', 'Pepsi Can (330 ml)', '330 ml', 40.0, 40.0, True)),
    _p('prod-matchbox', 'Homelite Safety Matchbox', 'household', _v('SPIN-MATCHBOX-10PK', 'Homelite Safety Matches (Pack of 10)', '10 pcs', 10.0, 10.0, True)),
]
