import { CustomerPersona } from "./types";

export const SIMULATED_CUSTOMERS: CustomerPersona[] = [
  // Bandra West (St 02)
  {
    id: "cust-karan-sharma",
    name: "Karan Sharma",
    homeStoreCode: "St 02",
    homeStoreName: "Bandra West",
    address: "Pali Hill, Bandra West, Mumbai",
    avatar: "KS",
    householdSize: 3,
    orderFrequencyDays: 2.5,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-mehta-family",
    name: "Mehta Family",
    homeStoreCode: "St 02",
    homeStoreName: "Bandra West",
    address: "Turner Road, Bandra West, Mumbai",
    avatar: "MF",
    householdSize: 4,
    orderFrequencyDays: 2.0,
    primaryDepletionItem: "Whole Wheat Bread 400g",
  },
  {
    id: "cust-joshi-home",
    name: "Joshi Home",
    homeStoreCode: "St 02",
    homeStoreName: "Bandra West",
    address: "Perry Cross Road, Bandra West, Mumbai",
    avatar: "JH",
    householdSize: 3,
    orderFrequencyDays: 3.0,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-khan-household",
    name: "Khan Household",
    homeStoreCode: "St 02",
    homeStoreName: "Bandra West",
    address: "Carter Road, Bandra West, Mumbai",
    avatar: "KH",
    householdSize: 5,
    orderFrequencyDays: 3.5,
    primaryDepletionItem: "Fresh Hybrid Tomatoes 500g",
  },
  {
    id: "cust-desai-family",
    name: "Desai Family",
    homeStoreCode: "St 02",
    homeStoreName: "Bandra West",
    address: "Waterfield Road, Bandra West, Mumbai",
    avatar: "DF",
    householdSize: 2,
    orderFrequencyDays: 4.0,
    primaryDepletionItem: "Farm Fresh Eggs (12 pcs)",
  },

  // Andheri East (St 01)
  {
    id: "cust-sharma-family",
    name: "Sharma Family",
    homeStoreCode: "St 01",
    homeStoreName: "Andheri East",
    address: "MIDC Cross Road, Andheri East, Mumbai",
    avatar: "SF",
    householdSize: 4,
    orderFrequencyDays: 2.5,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-patel-household",
    name: "Priya Patel",
    homeStoreCode: "St 01",
    homeStoreName: "Andheri East",
    address: "Chakala, Andheri East, Mumbai",
    avatar: "PP",
    householdSize: 2,
    orderFrequencyDays: 3.0,
    primaryDepletionItem: "Fresh Hybrid Tomatoes 500g",
  },
  {
    id: "cust-reddy-home",
    name: "Reddy Home",
    homeStoreCode: "St 01",
    homeStoreName: "Andheri East",
    address: "JB Nagar, Andheri East, Mumbai",
    avatar: "RH",
    householdSize: 3,
    orderFrequencyDays: 4.0,
    primaryDepletionItem: "Whole Wheat Bread 400g",
  },
  {
    id: "cust-singh-family",
    name: "Singh Family",
    homeStoreCode: "St 01",
    homeStoreName: "Andheri East",
    address: "Marol Naka, Andheri East, Mumbai",
    avatar: "SF",
    householdSize: 4,
    orderFrequencyDays: 3.5,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-das-house",
    name: "Das House",
    homeStoreCode: "St 01",
    homeStoreName: "Andheri East",
    address: "Sakinaka Junction, Andheri East, Mumbai",
    avatar: "DH",
    householdSize: 2,
    orderFrequencyDays: 5.0,
    primaryDepletionItem: "Farm Fresh Eggs (12 pcs)",
  },

  // Powai Galleria (St 03)
  {
    id: "cust-gupta-family",
    name: "Gupta Family",
    homeStoreCode: "St 03",
    homeStoreName: "Powai Galleria",
    address: "Hiranandani Gardens, Powai, Mumbai",
    avatar: "GF",
    householdSize: 4,
    orderFrequencyDays: 2.0,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-verma-home",
    name: "Verma Home",
    homeStoreCode: "St 03",
    homeStoreName: "Powai Galleria",
    address: "Central Avenue, Powai, Mumbai",
    avatar: "VH",
    householdSize: 3,
    orderFrequencyDays: 3.0,
    primaryDepletionItem: "Whole Wheat Bread 400g",
  },
  {
    id: "cust-iyer-household",
    name: "Ananya Iyer",
    homeStoreCode: "St 03",
    homeStoreName: "Powai Galleria",
    address: "Lake Boulevard, Powai, Mumbai",
    avatar: "AI",
    householdSize: 2,
    orderFrequencyDays: 4.0,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-bhatt-family",
    name: "Bhatt Family",
    homeStoreCode: "St 03",
    homeStoreName: "Powai Galleria",
    address: "Chandivali Farm Road, Powai, Mumbai",
    avatar: "BF",
    householdSize: 4,
    orderFrequencyDays: 3.5,
    primaryDepletionItem: "Fresh Hybrid Tomatoes 500g",
  },
  {
    id: "cust-shetty-house",
    name: "Shetty House",
    homeStoreCode: "St 03",
    homeStoreName: "Powai Galleria",
    address: "JVLR Junction, Powai, Mumbai",
    avatar: "SH",
    householdSize: 3,
    orderFrequencyDays: 5.0,
    primaryDepletionItem: "Farm Fresh Eggs (12 pcs)",
  },

  // Dadar / Lower Parel (St 04)
  {
    id: "cust-kulkarni-family",
    name: "Vikram Kulkarni",
    homeStoreCode: "St 04",
    homeStoreName: "Dadar / Lower Parel",
    address: "Senapati Bapat Marg, Lower Parel, Mumbai",
    avatar: "VK",
    householdSize: 3,
    orderFrequencyDays: 2.5,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-thakur-home",
    name: "Thakur Home",
    homeStoreCode: "St 04",
    homeStoreName: "Dadar / Lower Parel",
    address: "Shivaji Park, Dadar, Mumbai",
    avatar: "TH",
    householdSize: 4,
    orderFrequencyDays: 3.0,
    primaryDepletionItem: "Whole Wheat Bread 400g",
  },
  {
    id: "cust-rao-household",
    name: "Rao Household",
    homeStoreCode: "St 04",
    homeStoreName: "Dadar / Lower Parel",
    address: "Prabhadevi, Mumbai",
    avatar: "RH",
    householdSize: 3,
    orderFrequencyDays: 3.5,
    primaryDepletionItem: "Fresh Hybrid Tomatoes 500g",
  },
  {
    id: "cust-chopra-family",
    name: "Chopra Family",
    homeStoreCode: "St 04",
    homeStoreName: "Dadar / Lower Parel",
    address: "Parel Village, Lower Parel, Mumbai",
    avatar: "CF",
    householdSize: 2,
    orderFrequencyDays: 4.0,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-pillai-house",
    name: "Pillai House",
    homeStoreCode: "St 04",
    homeStoreName: "Dadar / Lower Parel",
    address: "Dadar TT Circle, Mumbai",
    avatar: "PH",
    householdSize: 5,
    orderFrequencyDays: 2.0,
    primaryDepletionItem: "Farm Fresh Eggs (12 pcs)",
  },

  // Thane West (St 05)
  {
    id: "cust-mishra-family",
    name: "Rahul Mishra",
    homeStoreCode: "St 05",
    homeStoreName: "Thane West",
    address: "Ghodbunder Road, Thane West, Mumbai",
    avatar: "RM",
    householdSize: 3,
    orderFrequencyDays: 3.0,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-saxena-home",
    name: "Saxena Home",
    homeStoreCode: "St 05",
    homeStoreName: "Thane West",
    address: "Majiwada, Thane West, Mumbai",
    avatar: "SH",
    householdSize: 4,
    orderFrequencyDays: 3.5,
    primaryDepletionItem: "Whole Wheat Bread 400g",
  },
  {
    id: "cust-pandey-household",
    name: "Pandey Household",
    homeStoreCode: "St 05",
    homeStoreName: "Thane West",
    address: "Panchpakhadi, Thane West, Mumbai",
    avatar: "PH",
    householdSize: 3,
    orderFrequencyDays: 4.0,
    primaryDepletionItem: "Fresh Hybrid Tomatoes 500g",
  },
  {
    id: "cust-dubey-family",
    name: "Dubey Family",
    homeStoreCode: "St 05",
    homeStoreName: "Thane West",
    address: "Vasant Vihar, Thane West, Mumbai",
    avatar: "DF",
    householdSize: 4,
    orderFrequencyDays: 5.0,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-trivedi-house",
    name: "Trivedi House",
    homeStoreCode: "St 05",
    homeStoreName: "Thane West",
    address: "Naupada, Thane West, Mumbai",
    avatar: "TH",
    householdSize: 5,
    orderFrequencyDays: 2.5,
    primaryDepletionItem: "Farm Fresh Eggs (12 pcs)",
  },
];

export const DEFAULT_CUSTOMER_PERSONA: CustomerPersona = SIMULATED_CUSTOMERS[0];

// ---------------------------------------------------------------------------
// OPERATIONS RESIDUE REMOVED — Phase 0 boundary cleanup
// INITIAL_STORES (DarkStore[]), INITIAL_RECOMMENDATIONS (RecommendationItem[]),
// and INITIAL_EVENTS (SimulationEvent[]) were removed.
// These belong in kwakhare5/Dark-store-operator.
// Source: GROCER_V2_MASTER_SPEC.md §19
// ---------------------------------------------------------------------------

