import { VerifiedJourneyTurn, FaqItem, PipelineNode } from "./types";

export const VERIFIED_JOURNEY_TURNS: VerifiedJourneyTurn[] = [
  {
    turn: 1,
    label: "Turn 1: Address Prompt",
    tag: "Upfront Choice",
    userInput: "i wanna make pasta under 1500",
    state: "NEEDS_DECISION",
    humanState: "Select Address",
    latencyMs: 0,
    assistantMessage: "Which address should I deliver this order to?\n\n1. Flat 402, Green Acres, Clover Park, Viman Nagar, Pune, Maharashtra\n2. Villa 12, Palm Meadows, Pancard Club Road, Baner, Pune, Maharashtra\n\nReply 1–2 to select your delivery address.",
    toolTrace: {
      tool: "get_saved_addresses",
      params: { customer_phone: "+919876543210" },
      resultSummary: "Checked saved addresses and prompted for upfront delivery selection before checking store inventory.",
      latencyMs: 0,
      invariantTested: "Upfront Multi-Address Disambiguation",
    },
  },
  {
    turn: 2,
    label: "Turn 2: Pasta Kit",
    tag: "Recipe Deduction",
    userInput: "2",
    state: "AWAITING_CHECKOUT_CONFIRMATION",
    humanState: "Review Basket",
    latencyMs: 1045,
    assistantMessage: "Updated delivery address to Villa 12, Palm Meadows, Pancard Club Road, Baner, Pune, Maharashtra.\n\nYour Basket (Baner, Pune):",
    items: [
      { name: "Yu Zero Maida Penne Pasta 500g", price: "Rs 49" },
      { name: "Veeba Pasta & Pizza Sauce 280g", price: "Rs 79" },
      { name: "Amul Mozzarella Diced Cheese 200g", price: "Rs 110" },
      { name: "Fresh Garlic 100g", price: "Rs 38" },
    ],
    subtotal: "Rs 276",
    fees: "Rs 5 (Handling)",
    total: "Rs 281",
    deliveryAddress: "Villa 12, Palm Meadows, Pancard Club Road, Baner, Pune, Maharashtra",
    toolTrace: {
      tool: "search_products",
      params: { query: "penne pasta sauce cheese garlic", budget_cap: 1500 },
      resultSummary: "Matched 4 in-stock ingredients at the Baner store. Total verified at Rs 281 with zero math hallucination.",
      latencyMs: 1045,
      invariantTested: "Recipe Ingredient Decomposition",
    },
  },
  {
    turn: 3,
    label: "Turn 3: Add Milk",
    tag: "Delta Cart Merge",
    userInput: "also add 1 amul milk 1L",
    state: "AWAITING_CHECKOUT_CONFIRMATION",
    humanState: "Review Basket",
    latencyMs: 820,
    assistantMessage: "Added Amul Taaza Milk 1L Pouch. Updated basket now has 5 items:",
    items: [
      { name: "Yu Zero Maida Penne Pasta 500g", price: "Rs 49" },
      { name: "Veeba Pasta & Pizza Sauce 280g", price: "Rs 79" },
      { name: "Amul Mozzarella Diced Cheese 200g", price: "Rs 110" },
      { name: "Fresh Garlic 100g", price: "Rs 38" },
      { name: "Amul Taaza Milk 1L Pouch", price: "Rs 66" },
    ],
    subtotal: "Rs 342",
    fees: "Rs 5 (Handling)",
    total: "Rs 347",
    deliveryAddress: "Villa 12, Palm Meadows, Pancard Club Road, Baner, Pune, Maharashtra",
    toolTrace: {
      tool: "update_cart",
      params: { action: "add", items: [{ sku: "amul_taaza_1l", quantity: 1 }] },
      resultSummary: "Added milk pouch to the active cart without wiping the 4 previous items. Basket total updated to Rs 347.",
      latencyMs: 820,
      invariantTested: "Delta Cart Merge (No Basket Wipe)",
    },
  },
  {
    turn: 4,
    label: "Turn 4: Hesitation Hold",
    tag: "Hesitation Guard",
    userInput: "wait",
    state: "AWAITING_CHECKOUT_CONFIRMATION",
    humanState: "Basket On Hold",
    latencyMs: 0,
    assistantMessage: "Basket kept on hold.\n\nYour groceries are saved. Whenever you're ready, let me know if you want to add/remove items, switch delivery address, or clear your basket.\n\nYour active basket has 5 items (Total Rs 347).",
    deliveryAddress: "Villa 12, Palm Meadows, Pancard Club Road, Baner, Pune, Maharashtra",
    toolTrace: {
      tool: "Hesitation Guard",
      params: { action: "hold_basket", active_items: 5, total: "Rs 347" },
      resultSummary: "Kept customer's basket intact when hesitation was detected. Zero accidental checkouts or basket resets.",
      latencyMs: 0,
      invariantTested: "Hesitation Hold Policy",
    },
  },
  {
    turn: 5,
    label: "Turn 5: Gated Checkout",
    tag: "Server Authorization",
    userInput: "Confirm",
    state: "AWAITING_PAYMENT",
    humanState: "Awaiting Payment",
    latencyMs: 640,
    assistantMessage: "Your order is ready. Complete payment via the official dark store UPI link:",
    paymentLink: "https://instamart.swiggy.com/pay/bridge/paas_mock_03a37382",
    toolTrace: {
      tool: "checkout",
      params: { is_user_confirmed: true, payment_method: "UPI" },
      resultSummary: "Authorized checkout only after explicit user confirmation. Generated official Swiggy UPI payment link.",
      latencyMs: 640,
      invariantTested: "Server-Side Checkout Gate",
    },
  },
  {
    turn: 6,
    label: "Turn 6: Clear Cart",
    tag: "Session Reset",
    userInput: "clear cart",
    state: "READY",
    humanState: "Basket Cleared",
    latencyMs: 0,
    assistantMessage: "Basket Cleared.\n\nYour basket is now completely empty. What groceries can I get for you today?",
    toolTrace: {
      tool: "clear_cart",
      params: { customer_phone: "+919876543210" },
      resultSummary: "Cleared all items from cart and reset the session state back to ready for the next order.",
      latencyMs: 0,
      invariantTested: "Basket Reset",
    },
  },
];

export const PIPELINE_NODES: PipelineNode[] = [
  {
    id: "whatsapp",
    stepNumber: "01",
    title: "WhatsApp Channel",
    subtitle: "Customer Ingress",
    badge: "Fast-Ack",
    badgeColor: "emerald",
    metric: "<200ms ACK",
    description: "Receives WhatsApp messages, verifies HMAC signatures, immediately sends read receipt (blue ticks), and queues text for processing.",
    technicalDetails: {
      protocol: "Meta Cloud Webhook • HMAC-SHA256",
      endpointOrFile: "backend/channels/whatsapp.py",
      invariants: [
        "HMAC signature verified before message parsing",
        "<200ms ACK returned to Meta Cloud to prevent retries",
        "Sender phone mapped to per-customer session lock",
      ],
      samplePayload: {
        object: "whatsapp_business_account",
        entry: [{
          changes: [{
            value: {
              messaging_product: "whatsapp",
              messages: [{ from: "919876543210", text: { body: "i wanna make pasta under 1500" } }],
            },
          }],
        }],
      },
    },
  },
  {
    id: "engine",
    stepNumber: "02",
    title: "FastAPI Engine",
    subtitle: "Turn Management",
    badge: "asyncio.Lock",
    badgeColor: "blue",
    metric: "Sequential Turns",
    description: "Serializes rapid texts using customer locks. Automatically requests address selection upfront if multiple saved locations exist.",
    technicalDetails: {
      protocol: "Python 3.12 Native Async Web Service",
      endpointOrFile: "backend/agent/engine.py & backend/agent/session.py",
      invariants: [
        "Concurrent texts serialized per phone number",
        "Upfront multi-address prompt if >1 saved address",
        "Session memory caches active cart ID and store metadata",
      ],
      samplePayload: {
        customer_phone: "919876543210",
        active_address_id: "ADDR_PUNE_BANER_012",
        lock_status: "ACQUIRED",
        turn_window: "6_TURNS_SLIDING",
      },
    },
  },
  {
    id: "gemini",
    stepNumber: "03",
    title: "Gemini 3.5 Flash-Lite",
    subtitle: "Language Reasoning",
    badge: "3-Model Failover",
    badgeColor: "purple",
    metric: "1,045ms Latency",
    description: "Interprets grocery requests, dietary constraints, and recipes. Executes parallel catalog searches via asyncio.gather.",
    technicalDetails: {
      protocol: "Google Generative AI Function Calling",
      endpointOrFile: "backend/agent/prompts.py & backend/agent/tools.py",
      invariants: [
        "Automatic 200ms failover: gemini-3.5-flash-lite -> flash-lite-latest -> 3-flash-preview",
        "Self-healing multi-turn history reset on malformed history",
        "Parallel tool calls executed concurrently via asyncio.gather",
      ],
      samplePayload: {
        model: "gemini-3.5-flash-lite",
        function_call: {
          name: "search_products",
          arguments: { query: "penne pasta sauce cheese garlic", budget_cap: 1500 },
        },
      },
    },
  },
  {
    id: "guards",
    stepNumber: "04",
    title: "Deterministic Guards",
    subtitle: "Safety & Policy",
    badge: "Fail-Closed",
    badgeColor: "emerald",
    metric: "100% Gated",
    description: "Pure Python code enforcing business rules: blocks checkout without confirmation, prevents premature delivery claims, and uses provider prices.",
    technicalDetails: {
      protocol: "Deterministic Runtime Enforcement",
      endpointOrFile: "backend/agent/guards.py & backend/agent/schemas.py",
      invariants: [
        "Unauthorized checkout calls physically rejected by server guard",
        "Fail-closed guard overrides false success claims on failed checkout",
        "Premature delivery claims blocked during payment pending status",
        "Prices, subtotals, and fees calculated solely by provider API",
      ],
      samplePayload: {
        is_user_confirmed: true,
        guard_evaluation: "PASSED",
        cart_total_calculated_by: "PROVIDER_BILLING_ENGINE",
        order_status: "AWAITING_PAYMENT",
      },
    },
  },
  {
    id: "swiggy",
    stepNumber: "05",
    title: "Swiggy Instamart MCP",
    subtitle: "Commerce Gateway",
    badge: "Official MCP",
    badgeColor: "orange",
    metric: "5 Live Tools",
    description: "Communicates over persistent connection pool with Swiggy Instamart's Model Context Protocol gateway to check inventory and update carts.",
    technicalDetails: {
      protocol: "Model Context Protocol (JSON-RPC 2.0)",
      endpointOrFile: "https://mcp.swiggy.com/im • backend/integrations/commerce/swiggy_adapter.py",
      invariants: [
        "Persistent connection pool eliminates TLS handshake per turn",
        "AES-GCM encrypted OAuth token storage with dynamic refresh",
        "Live tools: search_products, update_cart, get_cart, checkout, track_order",
      ],
      samplePayload: {
        jsonrpc: "2.0",
        method: "tools/call",
        params: {
          name: "checkout",
          arguments: { cart_id: "CART_IM_88291", generateUPIQR: true },
        },
      },
    },
  },
];

export const FAQ_ITEMS: FaqItem[] = [
  {
    question: "Can Grocer charge my account without my approval?",
    answer: "No. Grocer enforces a server-side lock. The checkout API is only called when you explicitly send or tap 'Confirm'. Payment is completed through official UPI links.",
  },
  {
    question: "How are prices and delivery fees calculated?",
    answer: "All prices, discounts, taxes, and fees come directly from Swiggy Instamart's billing API. The language model interprets what you need, while deterministic backend code computes totals.",
  },
  {
    question: "What happens if an item is out of stock?",
    answer: "If a requested item or brand is unavailable, Grocer checks dark store inventory for the closest in-stock alternative within your budget and asks for your approval before updating the basket.",
  },
  {
    question: "Can this work with other quick-commerce platforms?",
    answer: "Yes. Grocer is built around a decoupled CommercePort interface. Swiggy Instamart is our active reference integration via official MCP, but the architecture allows connecting other platforms.",
  },
  {
    question: "Why connect my Swiggy account here?",
    answer: "Connecting your account allows Grocer to load your saved delivery addresses and search real-time inventory from your local dark store directly inside WhatsApp.",
  },
];
