import { VerifiedJourneyTurn, VideoChapter, FaqItem, PipelineNode } from "./types";

export const VIDEO_CHAPTERS: VideoChapter[] = [
  { time: "0:00", label: "Address selection & prompt input" },
  { time: "0:35", label: "Recipe deduction & parallel search" },
  { time: "1:05", label: "Delta cart merge without basket wipe" },
  { time: "1:35", label: "Server-side gated checkout & UPI QR" },
  { time: "1:55", label: "Payment verification & order confirmation" },
];

export const VERIFIED_JOURNEY_TURNS: VerifiedJourneyTurn[] = [
  {
    turn: 1,
    label: "Turn 1: Address Prompt",
    tag: "Upfront Disambiguation",
    userInput: "i wanna make pasta under 1500",
    state: "NEEDS_DECISION",
    latencyMs: 0,
    assistantMessage: "Which address should I deliver this order to?\n\n1. Flat 402, Green Acres, Clover Park, Viman Nagar, Pune, Maharashtra\n2. Villa 12, Palm Meadows, Pancard Club Road, Baner, Pune, Maharashtra\n\nReply 1–2 to select your delivery address.",
    toolTrace: {
      tool: "get_saved_addresses",
      params: { customer_phone: "+919876543210" },
      resultSummary: "Detected 2 saved addresses. Guard intercepted before dark store routing to prevent delivering to the wrong hub.",
      latencyMs: 0,
      invariantTested: "INV-ADDR-01 (Upfront Multi-Address Disambiguation)",
    },
  },
  {
    turn: 2,
    label: "Turn 2: Pasta Kit",
    tag: "Recipe Deduction",
    userInput: "2",
    state: "AWAITING_CHECKOUT_CONFIRMATION",
    latencyMs: 1045,
    assistantMessage: "Updated delivery address to Villa 12, Palm Meadows, Pancard Club Road, Baner, Pune, Maharashtra.\n\nYour Basket (Baner, Pune):",
    items: [
      { name: "Yu Zero Maida Penne Pasta 500g", price: "Rs 49" },
      { name: "Veeba Pasta & Pizza Sauce 280g", price: "Rs 79" },
      { name: "Amul Mozzarella Diced Cheese 200g", price: "Rs 110" },
      { name: "Fresh Garlic 100g", price: "Rs 38" },
    ],
    subtotal: "Rs 276",
    fees: "Rs 5 (Handling)",
    total: "Rs 281",
    deliveryAddress: "Villa 12, Palm Meadows, Pancard Club Road, Baner, Pune, Maharashtra",
    toolTrace: {
      tool: "search_products",
      params: { query: "penne pasta sauce cheese garlic", budget_cap: 1500 },
      resultSummary: "Parallel catalog search matched 4 SKUs (in-stock at dark store #2041). Total Rs 281. Provider bill verified.",
      latencyMs: 1045,
      invariantTested: "INV-CART-01 (Parallel Recipe Decomposition & Math Verification)",
    },
  },
  {
    turn: 3,
    label: "Turn 3: Add Milk",
    tag: "Delta Cart Merge",
    userInput: "also add 1 amul milk 1L",
    state: "AWAITING_CHECKOUT_CONFIRMATION",
    latencyMs: 820,
    assistantMessage: "Added Amul Taaza Milk 1L Pouch. Updated basket now has 5 items:",
    items: [
      { name: "Yu Zero Maida Penne Pasta 500g", price: "Rs 49" },
      { name: "Veeba Pasta & Pizza Sauce 280g", price: "Rs 79" },
      { name: "Amul Mozzarella Diced Cheese 200g", price: "Rs 110" },
      { name: "Fresh Garlic 100g", price: "Rs 38" },
      { name: "Amul Taaza Milk 1L Pouch", price: "Rs 66" },
    ],
    subtotal: "Rs 342",
    fees: "Rs 5 (Handling)",
    total: "Rs 347",
    deliveryAddress: "Villa 12, Palm Meadows, Pancard Club Road, Baner, Pune, Maharashtra",
    toolTrace: {
      tool: "update_cart",
      params: { action: "add", items: [{ sku: "amul_taaza_1l", quantity: 1 }] },
      resultSummary: "Delta-merged milk pouch onto existing 4 items. Verified provider subtotal Rs 342. 5 items confirmed.",
      latencyMs: 820,
      invariantTested: "INV-CART-02 (Delta Cart Merge without Item Wipe)",
    },
  },
  {
    turn: 4,
    label: "Turn 4: Hesitation Hold",
    tag: "Hesitation Guard",
    userInput: "wait",
    state: "AWAITING_CHECKOUT_CONFIRMATION",
    latencyMs: 0,
    assistantMessage: "Basket kept on hold.\n\nYour groceries are saved. Whenever you're ready, let me know if you want to add/remove items, switch delivery address, or clear your basket.\n\nYour active basket has 5 items (Total Rs 347).",
    deliveryAddress: "Villa 12, Palm Meadows, Pancard Club Road, Baner, Pune, Maharashtra",
    toolTrace: {
      tool: "guards.py: HesitationHold",
      params: { input: "wait", active_cart_id: "CART_IM_88291" },
      resultSummary: "Deterministic hesitation guard intercepted user intent. Basket held intact with zero LLM API cost.",
      latencyMs: 0,
      invariantTested: "INV-GUARD-01 (Hesitation Guard)",
    },
  },
  {
    turn: 5,
    label: "Turn 5: Gated Checkout",
    tag: "Server Authorization",
    userInput: "Confirm",
    state: "AWAITING_PAYMENT",
    latencyMs: 640,
    assistantMessage: "Your order is ready. Complete payment via the official dark store UPI link:",
    paymentLink: "https://instamart.swiggy.com/pay/bridge/paas_mock_03a37382",
    toolTrace: {
      tool: "checkout",
      params: { is_user_confirmed: true, generateUPIQR: true },
      resultSummary: "Server authorization verified. Official Swiggy UPI bridge URL generated. 60s payment poller daemon started.",
      latencyMs: 640,
      invariantTested: "INV-CHECKOUT-01 (Server-Side Authorization Gate)",
    },
  },
  {
    turn: 6,
    label: "Turn 6: Clear Cart",
    tag: "Session Reset",
    userInput: "clear cart",
    state: "READY",
    latencyMs: 0,
    assistantMessage: "Basket Cleared.\n\nYour basket is now completely empty. What groceries can I get for you today?",
    toolTrace: {
      tool: "clear_cart",
      params: { customer_phone: "+919876543210" },
      resultSummary: "Session cart wiped clean. Customer session returned to READY state.",
      latencyMs: 0,
      invariantTested: "INV-CART-03 (State Reset)",
    },
  },
];

export const PIPELINE_NODES: PipelineNode[] = [
  {
    id: "whatsapp",
    stepNumber: "01",
    title: "WhatsApp Cloud API",
    subtitle: "Webhook Ingress",
    badge: "Fast-Ack",
    badgeColor: "emerald",
    metric: "<200ms Blue Ticks",
    description: "Receives Meta webhooks, validates HMAC signatures, immediately returns mark_message_read to trigger double blue ticks, and dispatches customer text.",
    technicalDetails: {
      protocol: "HTTPS Webhook • HMAC-SHA256",
      endpointOrFile: "backend/api/whatsapp.py & backend/channels/whatsapp.py",
      invariants: [
        "HMAC signature verified before payload parsing",
        "<200ms ACK returned to Meta Cloud to avoid webhook retries",
        "Sender phone mapped to per-customer session lock",
      ],
      samplePayload: {
        object: "whatsapp_business_account",
        entry: [{
          changes: [{
            value: {
              messaging_product: "whatsapp",
              messages: [{ from: "919876543210", text: { body: "i wanna make pasta under 1500" } }],
            },
          }],
        }],
      },
    },
  },
  {
    id: "engine",
    stepNumber: "02",
    title: "FastAPI Concurrency Lock",
    subtitle: "Turn Serialization",
    badge: "asyncio.Lock",
    badgeColor: "blue",
    metric: "0 Race Conditions",
    description: "Serializes rapid successive WhatsApp texts using per-customer locks. Prompts for address selection upfront if multiple saved addresses exist.",
    technicalDetails: {
      protocol: "Python 3.12 Native Async Web Service (Render)",
      endpointOrFile: "backend/agent/engine.py & backend/agent/session.py",
      invariants: [
        "Concurrent texts serialized per phone number",
        "Upfront multi-address disambiguation prompt if >1 saved address",
        "Session memory caches active cart ID and store metadata",
      ],
      samplePayload: {
        customer_phone: "919876543210",
        active_address_id: "ADDR_PUNE_BANER_012",
        lock_status: "ACQUIRED",
        turn_window: "6_TURNS_SLIDING",
      },
    },
  },
  {
    id: "gemini",
    stepNumber: "03",
    title: "Gemini 3.5 Flash-Lite",
    subtitle: "Reasoning & Tools",
    badge: "3-Model Failover",
    badgeColor: "purple",
    metric: "1,045ms Latency",
    description: "Extracts items and dietary constraints from plain English. Runs parallel product searches via asyncio.gather with automatic 200ms failover.",
    technicalDetails: {
      protocol: "Google Generative AI Function Calling • HTTP/2 Connection Pool",
      endpointOrFile: "backend/agent/prompts.py & backend/agent/tools.py",
      invariants: [
        "Automatic 200ms failover: gemini-3.5-flash-lite -> flash-lite-latest -> 3-flash-preview",
        "Self-healing multi-turn history reset on thought-signature errors",
        "Parallel tool calls executed concurrently via asyncio.gather",
      ],
      samplePayload: {
        model: "gemini-3.5-flash-lite",
        function_call: {
          name: "search_products",
          arguments: { query: "penne pasta sauce cheese garlic", budget_cap: 1500 },
        },
      },
    },
  },
  {
    id: "guards",
    stepNumber: "04",
    title: "Deterministic Safety Guards",
    subtitle: "Policy & Billing Enforcer",
    badge: "Fail-Closed",
    badgeColor: "emerald",
    metric: "100% Gated",
    description: "Pure Python code enforcing commerce rules: blocks checkout without confirmation, overrides false delivery claims, and calculates prices directly from provider data.",
    technicalDetails: {
      protocol: "Deterministic Python Runtime Enforcement",
      endpointOrFile: "backend/agent/guards.py & backend/agent/schemas.py",
      invariants: [
        "FM-CHECKOUT-01: Unauthorized checkout calls physically rejected by server guard",
        "FM-CHECKOUT-02: Fail-closed guard overrides false success claims on failed checkout",
        "FM-CHECKOUT-03: Premature delivery claims blocked during PAYMENT_PENDING status",
        "Prices, subtotals, and fees calculated solely by provider API",
      ],
      samplePayload: {
        is_user_confirmed: true,
        guard_evaluation: "PASSED",
        cart_total_calculated_by: "PROVIDER_BILLING_ENGINE",
        order_status: "AWAITING_PAYMENT",
      },
    },
  },
  {
    id: "swiggy",
    stepNumber: "05",
    title: "Swiggy Instamart Live MCP",
    subtitle: "CommercePort Reference",
    badge: "Official MCP",
    badgeColor: "orange",
    metric: "5 Live Tools",
    description: "Communicates over persistent HTTP/2 connection pool with Swiggy Instamart's Model Context Protocol gateway to query stock, update carts, and poll UPI QR payments.",
    technicalDetails: {
      protocol: "Model Context Protocol (JSON-RPC 2.0 over HTTP/2)",
      endpointOrFile: "https://mcp.swiggy.com/im • backend/integrations/commerce/swiggy_adapter.py",
      invariants: [
        "Persistent HTTP/2 pool eliminates TLS handshake per turn",
        "AES-GCM encrypted OAuth token storage with dynamic refresh",
        "Live tools: search_products, update_cart, get_cart, checkout, track_order",
      ],
      samplePayload: {
        jsonrpc: "2.0",
        method: "tools/call",
        params: {
          name: "checkout",
          arguments: { cart_id: "CART_IM_88291", generateUPIQR: true },
        },
      },
    },
  },
];

export const FAQ_ITEMS: FaqItem[] = [
  {
    question: "Can Grocer charge my account without my approval?",
    answer: "No. Grocer enforces a server-side lock. The checkout API is only called when you explicitly send or tap 'Confirm Order'. Payment is completed through official UPI links.",
  },
  {
    question: "How are prices and delivery fees calculated?",
    answer: "All prices, discounts, taxes, and fees are calculated directly by the dark store billing API. The language model interprets your request, while deterministic backend code computes totals.",
  },
  {
    question: "What happens if an item is out of stock?",
    answer: "If a requested brand is unavailable, Grocer checks dark store inventory for the closest in-stock alternative within your budget and asks for your approval before updating the basket.",
  },
  {
    question: "Can this work with other quick-commerce platforms?",
    answer: "Yes. Grocer uses a decoupled CommercePort interface. Swiggy Instamart is our active reference integration via official MCP. The architecture supports plugging in other platforms.",
  },
  {
    question: "Why connect my account on this website?",
    answer: "This domain (https://grocerr.vercel.app/) is the whitelisted OAuth redirect URI for Swiggy's MCP gateway. Authenticating here links your account so your WhatsApp session can access your local dark store.",
  },
];
