import { PresetScenario, VideoChapter, FaqItem, PipelineNode } from "./types";

export const VIDEO_CHAPTERS: VideoChapter[] = [
  { time: "0:00", label: "Address selection & prompt input" },
  { time: "0:35", label: "Recipe deduction & parallel search" },
  { time: "1:05", label: "Delta cart merge without basket wipe" },
  { time: "1:35", label: "Server-side gated checkout & UPI QR" },
  { time: "1:55", label: "Payment verification & order confirmation" },
];

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: "pasta",
    label: "Pasta Kit",
    tag: "Recipe Deduction",
    prompt: "I want to make pasta tonight under Rs 1500. Get ingredients",
    replyLead: "Penne Arbiatta ingredients from your local dark store:",
    items: [
      { name: "Yu Zero Maida Penne Pasta 500g", price: "Rs 49" },
      { name: "Veeba Pasta & Pizza Sauce 280g", price: "Rs 79" },
      { name: "Amul Mozzarella Diced Cheese 200g", price: "Rs 110" },
      { name: "Fresh Garlic 100g", price: "Rs 38" },
    ],
    subtotal: "Rs 276",
    fees: "Rs 5 (Handling)",
    total: "Rs 281",
    quickReplies: ["Confirm Order", "Also add butter", "Clear Cart"],
    toolTrace: {
      tool: "search_products",
      params: { query: "penne pasta sauce cheese garlic", max_price: 1500 },
      resultSummary: "Parallel catalog search matched 4 SKUs (in-stock at dark store #2041). Total Rs 281.",
      latencyMs: 1045,
    },
  },
  {
    id: "delta",
    label: "Delta Cart Merge",
    tag: "Cart Memory",
    prompt: "also add 1 amul milk 1L",
    replyLead: "Added Amul Taaza Milk 1L. Updated basket has 5 items:",
    items: [
      { name: "Yu Zero Maida Penne Pasta 500g", price: "Rs 49" },
      { name: "Veeba Pasta & Pizza Sauce 280g", price: "Rs 79" },
      { name: "Amul Mozzarella Diced Cheese 200g", price: "Rs 110" },
      { name: "Fresh Garlic 100g", price: "Rs 38" },
      { name: "Amul Taaza Milk 1L Pouch", price: "Rs 66" },
    ],
    subtotal: "Rs 342",
    fees: "Rs 5 (Handling)",
    total: "Rs 347",
    quickReplies: ["Confirm Order", "Remove cheese", "Clear Cart"],
    toolTrace: {
      tool: "update_cart",
      params: { action: "add", items: [{ sku: "amul_taaza_1l", quantity: 1 }] },
      resultSummary: "Delta-merged milk pouch onto existing 4 items. Verified provider subtotal Rs 342.",
      latencyMs: 820,
    },
  },
  {
    id: "staples",
    label: "Daily Staples",
    tag: "Restock",
    prompt: "Get 2L milk, whole wheat bread, and 6 eggs under Rs 500",
    replyLead: "Morning essentials added to your cart:",
    items: [
      { name: "Amul Taaza Fresh Toned Milk 1L (x2)", price: "Rs 132" },
      { name: "The Health Factory Zero Maida Bread 350g", price: "Rs 55" },
      { name: "Eggoz Farm Fresh White Eggs (Pack of 6)", price: "Rs 68" },
    ],
    subtotal: "Rs 255",
    fees: "FREE Delivery",
    total: "Rs 255",
    quickReplies: ["Confirm Order", "Add butter", "Change items"],
    toolTrace: {
      tool: "search_products",
      params: { items: ["toned milk 1L", "wheat bread", "eggs 6-pack"], budget_cap: 500 },
      resultSummary: "Resolved standard household variants. In-stock at local hub. Cart total Rs 255.",
      latencyMs: 910,
    },
  },
  {
    id: "care",
    label: "Cold Relief",
    tag: "Symptom Care",
    prompt: "Terrible cold and sore throat, my head is pounding",
    replyLead: "Cold comfort essentials from the pharmacy shelf:",
    items: [
      { name: "Strepsils Honey & Lemon Lozenges (8 pcs)", price: "Rs 45" },
      { name: "Vicks VapoRub Balm 25ml", price: "Rs 72" },
      { name: "Crocin Advance 500mg (Strip of 15)", price: "Rs 20" },
      { name: "Tetley Ginger & Mint Green Tea (10 bags)", price: "Rs 90" },
    ],
    subtotal: "Rs 227",
    fees: "FREE Delivery",
    total: "Rs 227",
    quickReplies: ["Confirm Order", "Remove Crocin", "Need tissues"],
    toolTrace: {
      tool: "search_products",
      params: { condition: "cold sore throat headache", otc_safe: true },
      resultSummary: "Deduced OTC wellness essentials. 10-15 min delivery dispatched.",
      latencyMs: 1120,
    },
  },
  {
    id: "checkout",
    label: "Confirm Checkout",
    tag: "Gated Payment",
    prompt: "Confirm",
    replyLead: "Order verified. Complete payment via the official dark store UPI link:",
    items: [],
    subtotal: "Rs 342",
    fees: "Rs 5",
    total: "Rs 347",
    quickReplies: ["Open UPI App", "Track Delivery Status"],
    toolTrace: {
      tool: "checkout",
      params: { is_user_confirmed: true, generateUPIQR: true },
      resultSummary: "Server confirmation verified. Dynamic UPI QR intent link generated: paas_bridge_49af52f6.",
      latencyMs: 640,
    },
  },
  {
    id: "track",
    label: "Track Order",
    tag: "Fulfillment",
    prompt: "Where is my order?",
    replyLead: "Rider Ramesh (Hero Splendor) picked up your order and is 4 minutes away.",
    items: [],
    subtotal: "",
    fees: "",
    total: "",
    quickReplies: ["Call Rider", "View Map"],
    toolTrace: {
      tool: "track_order",
      params: { order_id: "ORD_SWG_998124" },
      resultSummary: "Rider status: ON_THE_WAY. Dark store: Pune Hub #14. ETA: 4 mins.",
      latencyMs: 380,
    },
  },
];

export const PIPELINE_NODES: PipelineNode[] = [
  {
    id: "whatsapp",
    stepNumber: "01",
    title: "WhatsApp Cloud API",
    subtitle: "Webhook Ingress",
    badge: "Fast-Ack",
    badgeColor: "emerald",
    metric: "<200ms Blue Ticks",
    description: "Receives Meta webhooks, validates HMAC signatures, immediately returns mark_message_read to trigger double blue ticks, and dispatches customer text.",
    technicalDetails: {
      protocol: "HTTPS Webhook • HMAC-SHA256",
      endpointOrFile: "backend/api/whatsapp.py & backend/channels/whatsapp.py",
      invariants: [
        "HMAC signature verified before payload parsing",
        "<200ms ACK returned to Meta Cloud to avoid webhook retries",
        "Sender phone mapped to per-customer session lock",
      ],
      samplePayload: {
        object: "whatsapp_business_account",
        entry: [{
          changes: [{
            value: {
              messaging_product: "whatsapp",
              messages: [{ from: "919876543210", text: { body: "i wanna make pasta under 1500" } }],
            },
          }],
        }],
      },
    },
  },
  {
    id: "engine",
    stepNumber: "02",
    title: "FastAPI Concurrency Lock",
    subtitle: "Turn Serialization",
    badge: "asyncio.Lock",
    badgeColor: "blue",
    metric: "0 Race Conditions",
    description: "Serializes rapid successive WhatsApp texts using per-customer locks. Prompts for address selection upfront if multiple saved addresses exist.",
    technicalDetails: {
      protocol: "Python 3.12 Native Async Web Service (Render)",
      endpointOrFile: "backend/agent/engine.py & backend/agent/session.py",
      invariants: [
        "Concurrent texts serialized per phone number",
        "Upfront multi-address disambiguation prompt if >1 saved address",
        "Session memory caches active cart ID and store metadata",
      ],
      samplePayload: {
        customer_phone: "919876543210",
        active_address_id: "ADDR_PUNE_CHARHOLI_704",
        lock_status: "ACQUIRED",
        turn_window: "6_TURNS_SLIDING",
      },
    },
  },
  {
    id: "gemini",
    stepNumber: "03",
    title: "Gemini 3.5 Flash-Lite",
    subtitle: "Reasoning & Tools",
    badge: "3-Model Failover",
    badgeColor: "purple",
    metric: "1,045ms Latency",
    description: "Extracts items and dietary constraints from plain English. Runs parallel product searches via asyncio.gather with automatic 200ms failover.",
    technicalDetails: {
      protocol: "Google Generative AI Function Calling • HTTP/2 Connection Pool",
      endpointOrFile: "backend/agent/prompts.py & backend/agent/tools.py",
      invariants: [
        "Automatic 200ms failover: gemini-3.5-flash-lite -> flash-lite-latest -> 3-flash-preview",
        "Self-healing multi-turn history reset on thought-signature errors",
        "Parallel tool calls executed concurrently via asyncio.gather",
      ],
      samplePayload: {
        model: "gemini-3.5-flash-lite",
        function_call: {
          name: "search_products",
          arguments: { query: "penne pasta sauce cheese garlic", budget_cap: 1500 },
        },
      },
    },
  },
  {
    id: "guards",
    stepNumber: "04",
    title: "Deterministic Safety Guards",
    subtitle: "Policy & Billing Enforcer",
    badge: "Fail-Closed",
    badgeColor: "emerald",
    metric: "100% Gated",
    description: "Pure Python code enforcing commerce rules: blocks checkout without confirmation, overrides false delivery claims, and calculates prices directly from provider data.",
    technicalDetails: {
      protocol: "Deterministic Python Runtime Enforcement",
      endpointOrFile: "backend/agent/guards.py & backend/agent/schemas.py",
      invariants: [
        "FM-CHECKOUT-01: Unauthorized checkout calls physically rejected by server guard",
        "FM-CHECKOUT-02: Fail-closed guard overrides false success claims on failed checkout",
        "FM-CHECKOUT-03: Premature delivery claims blocked during PAYMENT_PENDING status",
        "Prices, subtotals, and fees calculated solely by provider API",
      ],
      samplePayload: {
        is_user_confirmed: true,
        guard_evaluation: "PASSED",
        cart_total_calculated_by: "PROVIDER_BILLING_ENGINE",
        order_status: "AWAITING_PAYMENT",
      },
    },
  },
  {
    id: "swiggy",
    stepNumber: "05",
    title: "Swiggy Instamart Live MCP",
    subtitle: "CommercePort Reference",
    badge: "Official MCP",
    badgeColor: "orange",
    metric: "5 Live Tools",
    description: "Communicates over persistent HTTP/2 connection pool with Swiggy Instamart's Model Context Protocol gateway to query stock, update carts, and poll UPI QR payments.",
    technicalDetails: {
      protocol: "Model Context Protocol (JSON-RPC 2.0 over HTTP/2)",
      endpointOrFile: "https://mcp.swiggy.com/im • backend/integrations/commerce/swiggy_adapter.py",
      invariants: [
        "Persistent HTTP/2 pool eliminates TLS handshake per turn",
        "AES-GCM encrypted OAuth token storage with dynamic refresh",
        "Live tools: search_products, update_cart, get_cart, checkout, track_order",
      ],
      samplePayload: {
        jsonrpc: "2.0",
        method: "tools/call",
        params: {
          name: "checkout",
          arguments: { cart_id: "CART_IM_88291", generateUPIQR: true },
        },
      },
    },
  },
];

export const FAQ_ITEMS: FaqItem[] = [
  {
    question: "Can Grocer charge my account without my approval?",
    answer: "No. Grocer enforces a server-side lock. The checkout API is only called when you explicitly send or tap 'Confirm Order'. Payment is completed through official UPI links.",
  },
  {
    question: "How are prices and delivery fees calculated?",
    answer: "All prices, discounts, taxes, and fees are calculated directly by the dark store billing API. The language model interprets your request, while deterministic backend code computes totals.",
  },
  {
    question: "What happens if an item is out of stock?",
    answer: "If a requested brand is unavailable, Grocer checks dark store inventory for the closest in-stock alternative within your budget and asks for your approval before updating the basket.",
  },
  {
    question: "Can this work with other quick-commerce platforms?",
    answer: "Yes. Grocer uses a decoupled CommercePort interface. Swiggy Instamart is our active reference integration via official MCP. The architecture supports plugging in other platforms.",
  },
  {
    question: "Why connect my account on this website?",
    answer: "This domain (https://grocerr.vercel.app/) is the whitelisted OAuth redirect URI for Swiggy's MCP gateway. Authenticating here links your account so your WhatsApp session can access your local dark store.",
  },
];
